### ISSUE TITLE
Suggestion: Transferable Information to New Phone

### ISSUE THREAD

**Issue by tiscott1** [soren121/yodel#101]
I always hear people complain on Yik Yak about losing all their yakarma once they update their phone. With Windows Phone 10 fast approaching, many of us will be upgrading to a shiny, new Talkman or Cityman.

I suggest using someway of allowing users to migrate their Yak ID to a new install (similar to the way we transferred from the beta).

**Comment by soren121** [comment]
There's no need, actually. Your user ID is stored in roaming storage, so it's tied to your Microsoft account and saved in the cloud. When you get a new phone, you'll keep your yakarma.

People using the official Yik Yak apps lose their yakarma because YY generates their ID from information about their phone, such as the IMEI, their phone number, etc. Yodel generates your ID randomly and saves it in the cloud.

**Comment by PatrickMurphy** [comment]
Very cool, thanks for the explanation. So the only reason beta -> 1.0 needed it was because they are technically different apps and can not read each others roaming data correct?

**Comment by soren121** [comment]
Correct!
