### ISSUE TITLE
Messages not saving/Recent Yaks list is empty/"We ran into a problem" message

### ISSUE THREAD

**Issue by clevbolt** [soren121/yodel#37]
I don't believe they are saving. When I exit off the app and come back everything that was commented/posted is gone. And when you comment on a post twice the first one is deleted.

**Comment by jeffshi** [comment]
I've tried posting for the first time today and some of the issues mentioned in the thread occur for me as well. I make a post and can see it in the feed, but when I check my recent and top yaks lists, there's nothing. My post disappears from the feed when I exit out and reopen the app.

**Comment by Haddaddy** [comment]
Idk why but since I've been on break and not in the area I downloaded yodel, I have been able to post multiple messages and received replies and up or down votes. I know this isn't very beneficial but it works and idk why.

**Comment by em74** [comment]
Yup, all my yaks are being deleted at around the 1min mark.

**Comment by Paperpals** [comment]
Alright so I have a friend who has Yik Yak on Android and I had him help me. I'd make a Yak and it would never show up. He would make a Yak and I could see it on the Windows phone though. I'd then try to comment on his yak and it wouldn't show anything. I noticed that when I commented on his Yak though, I could see it on my phone until the App is closed, but he couldn't see it at all. When if I went and tried to comment on a different Yak though, the first one would disappear. The new one would still have the same problem though, as being invisible to everyone except me and disappear if the app is closed.

As for making my own Yaks, as I said he couldn't see them. Like the commenting on Yaks, they aren't visible to anyone else and I can't see them anymore after I close the app. It seems that when I create a yak or comment on a yak, my Yakarma score increases (because I believe it increases every time you comment or make a yak, as well as getting upvotes.)

**Comment by clevbolt** [comment]
Yeah, this seems to be the problem all around with the beta testers.

**Comment by RoboMWM** [comment]
It seems to happen to "new" users - after a while it started working. Not exactly sure what triggered this, but it was before the break so I don't think it's location-related...

**Comment by ChromeShield** [comment]
Also having this problem

**Comment by MeganC121** [comment]
All of the above mentioned issues I am experiencing. None of my yaks or comments stay on the feed, and they are not visible in my yaks. However my yakarama thing increases when I post a yak, even when it is no longer visible. I just became a beta tester yesterday (2/6/15). It is a relief however to see that I am not the only person struggling with this!

**Comment by soren121** [comment]
I'm locking this issue for now.

**Comment by soren121** [comment]
I hope you're all ready for the update tonight that fixes just about everything you wanted :)

**Comment by clevbolt** [comment]
I'm pumped!!

-----Original Message-----

**Comment by BlueIsTheColour** [comment]
:D Any estimate on what time tonight it'll be released?

**Comment by soren121** [comment]
Probably quite late.
