### ISSUE TITLE
Comment icons do not appear on the Lumia Icon

### ISSUE THREAD

**Issue by toadsonone** [soren121/yodel#97]
I was redirected here from reddit a while ago. Evidently, the app was updated so that icons appear on the comments however I am running the app on a Lumia Icon and they do not appear.

**Comment by soren121** [comment]
What version number is shown in the About section on the app's settings page?

**Comment by toadsonone** [comment]
0.9.6.0

**Comment by soren121** [comment]
Oh! Oh no. You're still using the beta version. The beta was abandoned four months ago when I released version 1.0. Unfortunately, due to the way the Store handles beta apps, I had to release the public version as a new app.

Download the public version here: https://www.windowsphone.com/s?appid=9b3e9c28-18cc-460b-9c83-b3d44d62dc83
